apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: helmocisample
  namespace: flux-system
spec:
  interval: 10m0s
  url: 702834246803.dkr.ecr.us-west-2.amazonaws.com/helm-oci-image
